apiVersion: v1
kind: Pod
metadata:
  name: pets-rag
  namespace: pets
  labels:
    app: RAG
spec:
  containers:
  - image: mapgirll/pets:pets-python-rag-amd64
    command: ["/bin/sleep"]  # Sleep command to keep the container running
    args: ["infinity"]  # Sleep indefinitely to prevent the container from exiting
    env:
    - name: OPENAI_API_KEY
      value: sk-
    - name: STORE-ADMIN-IP
      value: X.X.X.X
    imagePullPolicy: Always
    name: pets-rag
  restartPolicy: Always